/*
  DO NOT EDIT THIS FILE!
  Classes and tests should be in separate files.
  Click Run to run the tests.

  Instructions are in README.txt
*/

var Jasmine = require('jasmine');
var jasmine = new Jasmine();

jasmine.loadConfig({
  	spec_dir: 'spec',
  	spec_files: [
    	"**/*[sS]pec.js"
  	],
});

jasmine.execute();